debug:   true

cdn:
  host: https://cdn-testnet.zildexr.com

ingress:
  host: api-testnet.zildexr.com

replicaCount: 2

db:
  dialect:  postgresql
  username: postgres
  password: TQN4EGYenx
  host:     postgres-zilkroad.postgres.svc.cluster.local
  port:     5432
  name:     zildexr
  schema:   testnet