apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      imagePullSecrets:
        - name: aws-registry
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/api"]
          volumeMounts:
            - name: configmap
              mountPath: /app/env.yaml
              subPath: env.yaml
        - name: openresty
          image: openresty/openresty:1.19.9.1-9-alpine-fat
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: configmap
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: cache
              mountPath: /cache
            - name: audit
              mountPath: {{ .Values.audit.dir }}
        - name: filebeat
          image: elastic/filebeat:7.17.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: audit
              mountPath: {{ .Values.audit.dir }}
            - name: configmap
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
      volumes:
        - name: configmap
          configMap:
            name: {{ .Release.Name }}-configmap
        - name:  audit
          emptyDir: {}
        - name:  cache
          emptyDir: {}