NETWORK: zilliqa
INDEX_NAME: mainnet

DEBUG: true

ELASTIC_SEARCH_AWS: true
ELASTIC_SEARCH_HOSTS: https://search-zilkroad-index-wlmccxpkwz6ps7sohqqjvdphqa.us-east-1.es.amazonaws.com
ELASTIC_SEARCH_SNIFF: false
ELASTIC_SEARCH_HEALTH_CHECK: false
ELASTIC_SEARCH_DEBUG: false

AWS_ACCESS_KEY: awsAccessKeyId
AWS_SECRET_KEY: awsSecretAccessKey
AWS_REGION: us-east-1

PORT: 8082

CACHE: false
SUBSCRIBE: false

SENTRY_DSN: sentryDsn