NETWORK: zilliqa
INDEX_NAME: mainnet

DEBUG: true

ELASTIC_SEARCH_AWS: true
ELASTIC_SEARCH_HOSTS: %ELASTIC_SEARCH_HOST%
ELASTIC_SEARCH_SNIFF: false
ELASTIC_SEARCH_HEALTH_CHECK: false
ELASTIC_SEARCH_DEBUG: false

AWS_ACCESS_KEY: %AWS_ACCESS_KEY_ID%
AWS_SECRET_KEY: %AWS_SECRET_ACCESS_KEY%
AWS_TOKEN:
AWS_REGION: us-east-1

PORT: 8082

CACHE: false
SUBSCRIBE: false

SENTRY_DSN: %SENTRY_DSN%