DEBUG: false

ELASTIC_SEARCH_AWS: true
ELASTIC_SEARCH_HOST: "https://search-zilkroad-index-5yazp27hjzc6jrl4cuqw5t6nau.eu-west-1.es.amazonaws.com"
ELASTIC_SEARCH_SNIFF: false
ELASTIC_SEARCH_HEALTH_CHECK: false
ELASTIC_SEARCH_DEBUG: false

AWS_ES_ACCESS_KEY: awsAccessKeyId
AWS_ES_SECRET_KEY: awsSecretAccessKey
AWS_ES_REGION: eu-west-1

PORT: 80

SENTRY_DSN: sentryDsn