DEBUG: false

ELASTIC_SEARCH_AWS: true
ELASTIC_SEARCH_HOST: "https://search-zilkroad-index-wlmccxpkwz6ps7sohqqjvdphqa.us-east-1.es.amazonaws.com"
ELASTIC_SEARCH_SNIFF: false
ELASTIC_SEARCH_HEALTH_CHECK: false
ELASTIC_SEARCH_DEBUG: false

AWS_ES_ACCESS_KEY: awsAccessKeyId
AWS_ES_SECRET_KEY: awsSecretAccessKey
AWS_ES_REGION: us-east-1

PORT: 8082

SENTRY_DSN: sentryDsn