image:
  repository: 981130112916.dkr.ecr.us-east-1.amazonaws.com/zildexr/public-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

debug:   false

elasticSearch:
  host:        https://search.zildexr.com
  username:    elastic
  password:    gyXGCRTvHuNjLKEXQUH98kggRLEfH6rP
  sniff:       false
  healthCheck: false
  debug:       false

db:
  dialect:  postgresql
  port:     5432
  username: ~
  password: ~
  host:     ~
  name:     ~
  schema:   ~
  ssl_mode: ~
  options:  ~
  root_ca:  ~

aws:
  access_key: AKIAWY3PIDKSWL5ICD7E
  secret_key: 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
  region:     us-east-1

audit:
  dir: /var/audit

resources:
  requests:
    cpu: 0
    memory: 0M
  limits:
    cpu: 0.2
    memory: 512M
