replicaCount: 0

image:
  repository: 465700395685.dkr.ecr.eu-west-1.amazonaws.com/indexer/api-docs
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  host: ~

resources:
  requests:
    cpu: 0
    memory: 0M
  limits:
    cpu: 0.1
    memory: 512M
