replicaCount: 0

image:
  repository: 981130112916.dkr.ecr.us-east-1.amazonaws.com/indexer/api-docs
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  host: ~

resources:
  requests:
    cpu: 0
    memory: 0M
  limits:
    cpu: 0.1
    memory: 512M
