name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required:    true
        description: Which environment to deploy?
        type:        choice
        options:
          - testnet
          - mainnet
      tag:
        required:    true
        description: ECR tag
        default:     latest

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Load Automation
        uses: actions/checkout@v2
        with:
          repository: ZilDuck/automation
          ref: master
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ./automation
      - name: Deploy
        uses: ./automation/workflow/deploy
        with:
          app:         zildexr
          service:     api
          environment: ${{ github.event.inputs.environment }}
          tag:         ${{ github.event.inputs.tag }}