name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required:    true
        description: Which environment to deploy?
        type:        choice
        options:
          - testnet
          - mainnet
      tag:
        required:    true
        description: ECR tag
        default:     latest

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Load Automation
        uses: actions/checkout@v2
        with:
          repository: ZilDuck/automation@master
          token: ${{ secrets.ACCESS_TOKEN }}
          path: ../actions/deploy
      - name: Deploy
        uses: ../actions/deploy
        with:
          app:         zildexr
          service:     api
          environment: ${{ github.event.inputs.environment }}
          tag:         ${{ github.event.inputs.tag }}