name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required:    true
        description: Which environment to deploy?
        type:        choice
        options:
          - testnet
          - mainnet
      tag:
        required:    true
        description: ECR tag
        default:     latest

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          name: ZilDuck/indexer-automation
      - name: Helm
        uses: 'deliverybot/helm@v1'
        with:
          namespace: zildexr-staging
          chart:     ./deployments/zildexr/api
          values: "{image.tag: ${{ github.event.inputs.tag }}}"

