name: Deploy Indexer API

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  printInputs:
    runs-on: self-hosted
    steps:
      - run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"