name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required:    true
        description: Which environment to deploy?
        type:        choice
        options:
          - testnet
          - mainnet
      tag:
        required:    true
        description: ECR tag
        default:     latest
env:
  APP: zildexr
  SERVICE: api

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.inputs.tag }}

      - name: Deploy API to Kubernetes
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install ${{ env.SERVICE }} api/.helm -f api/.helm/config/${{ github.event.inputs.environment }}.yaml --namespace ${{ env.APP }}-${{ github.event.inputs.environment }} --atomic --set=image.tag=${{ github.event.inputs.tag }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'

      - name: Deploy Docs to Kubernetes
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install ${{ env.SERVICE }}-docs docs/.helm -f docs/.helm/config/${{ github.event.inputs.environment }}.yaml --namespace ${{ env.APP }}-${{ github.event.inputs.environment }} --atomic --set=image.tag=${{ github.event.inputs.tag }}
          kubeconfig: '${{ secrets.KUBECONFIG }}'